name: Semgrep scan

on:
  pull_request:
    branches:
      - main

#prevent race conditions/concurrency  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep:
    name: Semgrep PR scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep ci

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif 